//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Seguros.Sepelio.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class panelEntities : DbContext
    {
        public panelEntities()
            : base("name=panelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Seguridad_Aplicacion> Seguridad_Aplicacion { get; set; }
        public virtual DbSet<SEGURIDAD_TERMINOS_CONDICIONES> SEGURIDAD_TERMINOS_CONDICIONES { get; set; }
        public virtual DbSet<tbl_aSEGUROSEPELIO_PASO_TRANSACCION> tbl_aSEGUROSEPELIO_PASO_TRANSACCION { get; set; }
        public virtual DbSet<tbl_aSEGUROSEPELIO_SEXO> tbl_aSEGUROSEPELIO_SEXO { get; set; }
        public virtual DbSet<tbl_aSEGUROSEPELIO_TIPO_PLAN> tbl_aSEGUROSEPELIO_TIPO_PLAN { get; set; }
        public virtual DbSet<tbl_aSEGUROSEPELIO_TIPO_TRANSACCION> tbl_aSEGUROSEPELIO_TIPO_TRANSACCION { get; set; }
        public virtual DbSet<tbl_aSEGUROSEPELIO_UBIGEO_CIUDAD> tbl_aSEGUROSEPELIO_UBIGEO_CIUDAD { get; set; }
        public virtual DbSet<tbl_aSEGUROSEPELIO_UBIGEO_DISTRIT> tbl_aSEGUROSEPELIO_UBIGEO_DISTRIT { get; set; }
        public virtual DbSet<tbl_aSEGUROSEPELIO_UBIGEO_PROV> tbl_aSEGUROSEPELIO_UBIGEO_PROV { get; set; }
        public virtual DbSet<tbl_mSEGUROSEPELIO_CLIENTE> tbl_mSEGUROSEPELIO_CLIENTE { get; set; }
        public virtual DbSet<tbl_mSEGUROSEPELIO_TOKEN> tbl_mSEGUROSEPELIO_TOKEN { get; set; }
        public virtual DbSet<tbl_aSEGUROSEPELIO_CONYUGUE> tbl_aSEGUROSEPELIO_CONYUGUE { get; set; }
        public virtual DbSet<tbl_aSEGUROSEPELIO_TERCERO> tbl_aSEGUROSEPELIO_TERCERO { get; set; }
        public virtual DbSet<tbl_mSEGUROSEPELIO_TRANSACCION> tbl_mSEGUROSEPELIO_TRANSACCION { get; set; }
        public virtual DbSet<tbl_mSEGUROSEPELIO_LOG> tbl_mSEGUROSEPELIO_LOG { get; set; }
    
        public virtual int SP_SEGUROSEPELIO_ACTUALIZACONSENTIMIENTO(Nullable<int> cODIGOCLIENTE, Nullable<int> fLAG)
        {
            var cODIGOCLIENTEParameter = cODIGOCLIENTE.HasValue ?
                new ObjectParameter("CODIGOCLIENTE", cODIGOCLIENTE) :
                new ObjectParameter("CODIGOCLIENTE", typeof(int));
    
            var fLAGParameter = fLAG.HasValue ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SEGUROSEPELIO_ACTUALIZACONSENTIMIENTO", cODIGOCLIENTEParameter, fLAGParameter);
        }
    }
}
