//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Seguros.Sepelio.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGURIDAD_TERMINOS_CONDICIONES
    {
        public int TERMINOS_ID { get; set; }
        public Nullable<int> APLICACION_ID { get; set; }
        public string CONTENIDO { get; set; }
        public string CONTENIDO_2 { get; set; }
        public string CONTENIDO_3 { get; set; }
    }
}
