//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Seguros.Sepelio.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mSEGUROSEPELIO_LOG
    {
        public int CODIGO_LOG { get; set; }
        public string CODIGO_UNICO { get; set; }
        public Nullable<int> CODIGOCLIENTE { get; set; }
        public Nullable<int> CODIGO_PASO { get; set; }
        public string DETALLE_LOG { get; set; }
        public Nullable<System.DateTime> FECHA_LOG { get; set; }
        public string IP_CLIENTE { get; set; }
    }
}
