//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Seguros.Sepelio.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aSEGUROSEPELIO_PASO_TRANSACCION
    {
        public int CODIGO_PASO { get; set; }
        public string CODIGO_TIPO_TRANSACCION { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        public virtual tbl_aSEGUROSEPELIO_TIPO_TRANSACCION tbl_aSEGUROSEPELIO_TIPO_TRANSACCION { get; set; }
    }
}
