//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Seguros.Sepelio.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mSEGUROSEPELIO_TRANSACCION
    {
        public int CODIGOTRANSACCION { get; set; }
        public Nullable<int> CODIGOCLIENTE { get; set; }
        public string NOMBRECLIENTE { get; set; }
        public string CODIGO_TIPO_TRANSACCION { get; set; }
        public Nullable<int> ATENTIDO { get; set; }
        public Nullable<System.DateTime> FECHA_ATENCION { get; set; }
        public Nullable<System.DateTime> FECHA_TRANSACCION { get; set; }
        public string FLAG_CORREO { get; set; }
        public string USUARIO_ATENCION { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<int> CODIGOTIPOPLAN { get; set; }
        public Nullable<int> CODIGOCONYUGUE { get; set; }
        public string NOMBRECONYUGUE { get; set; }
        public Nullable<int> CODIGOTERCERO { get; set; }
        public string NOMBRETERCERO { get; set; }
        public Nullable<int> CODIGO_PROCESO { get; set; }
        public Nullable<bool> CARGO_TARJETA { get; set; }
        public Nullable<bool> CARGO_TARJETA_DIA { get; set; }
        public Nullable<bool> TERMINOS_CONDICIONES { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string CERTIFICADO { get; set; }
        public string NOMBRETERCERO2 { get; set; }
        public Nullable<int> CODIGOTERCERO2 { get; set; }
    
        public virtual tbl_aSEGUROSEPELIO_CONYUGUE tbl_aSEGUROSEPELIO_CONYUGUE { get; set; }
        public virtual tbl_aSEGUROSEPELIO_TERCERO tbl_aSEGUROSEPELIO_TERCERO { get; set; }
        public virtual tbl_aSEGUROSEPELIO_TIPO_PLAN tbl_aSEGUROSEPELIO_TIPO_PLAN { get; set; }
        public virtual tbl_aSEGUROSEPELIO_TIPO_TRANSACCION tbl_aSEGUROSEPELIO_TIPO_TRANSACCION { get; set; }
        public virtual tbl_mSEGUROSEPELIO_CLIENTE tbl_mSEGUROSEPELIO_CLIENTE { get; set; }
    }
}
