//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Seguros.Sepelio.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aSEGUROSEPELIO_TIPO_TRANSACCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_aSEGUROSEPELIO_TIPO_TRANSACCION()
        {
            this.tbl_aSEGUROSEPELIO_PASO_TRANSACCION = new HashSet<tbl_aSEGUROSEPELIO_PASO_TRANSACCION>();
            this.tbl_mSEGUROSEPELIO_TRANSACCION = new HashSet<tbl_mSEGUROSEPELIO_TRANSACCION>();
        }
    
        public string CODIGO_TIPO_TRANSACCION { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_aSEGUROSEPELIO_PASO_TRANSACCION> tbl_aSEGUROSEPELIO_PASO_TRANSACCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mSEGUROSEPELIO_TRANSACCION> tbl_mSEGUROSEPELIO_TRANSACCION { get; set; }
    }
}
