//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Seguros.Sepelio.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aSEGUROSEPELIO_SEXO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_aSEGUROSEPELIO_SEXO()
        {
            this.tbl_aSEGUROSEPELIO_CONYUGUE = new HashSet<tbl_aSEGUROSEPELIO_CONYUGUE>();
            this.tbl_aSEGUROSEPELIO_TERCERO = new HashSet<tbl_aSEGUROSEPELIO_TERCERO>();
        }
    
        public int CODIGOSEXO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_aSEGUROSEPELIO_CONYUGUE> tbl_aSEGUROSEPELIO_CONYUGUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_aSEGUROSEPELIO_TERCERO> tbl_aSEGUROSEPELIO_TERCERO { get; set; }
    }
}
